# Model and paths
pretrained_model_name_or_path: "botp/stable-diffusion-v1-5"
controlnet_model_name_or_path: null
revision: null
variant: null
tokenizer_name: null
cache_dir: null
resume_from_checkpoint: null
output_dir: "outputs/mv_controlnet-train"
noise_offset: 0

# Dataset configurations
train_dataset:
  root_dir_ortho: 'datapath/ortho-13views'
  root_dir_persp: 'datapath/persp-13views'
  pred_ortho: true
  pred_persp: false
  object_list: "./datalist/datalist_single_obj.json"
  invalid_list: null
  num_views: 4
  groups_num: 1
  bg_color: "white"
  img_wh: [256, 256]
  validation: false
  num_validation_samples: 8
  read_normal: false
  read_color: true
  pred_type: "mixed_rgb_normal_depth"
  load_cam_type: true

validation_dataset:
  root_dir_ortho: 'datapath/ortho-13views'
  root_dir_persp: 'datapath/persp-13views'
  pred_ortho: true
  pred_persp: false
  object_list: "./datalist/datalist_single_obj.json"
  invalid_list: null
  num_views: 4
  groups_num: 1
  bg_color: "white"
  img_wh: [256, 256]
  validation: true
  num_validation_samples: 8
  read_normal: false
  read_color: true
  pred_type: "mixed_rgb_normal_depth"
  load_cam_type: true

# Training parameters
pred_type: "joint"
seed: 42
resolution: 1024
train_batch_size: 4
validation_batch_size: 1
validation_train_batch_size: 2
max_train_steps: null
num_train_epochs: 40
gradient_accumulation_steps: 1
gradient_checkpointing: false
learning_rate: 1e-5
scale_lr: false
lr_scheduler: "constant"
lr_warmup_steps: 500
lr_num_cycles: 1
lr_power: 1.0
snr_gamma: 5
use_8bit_adam: false
allow_tf32: true
dataloader_num_workers: 16
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 1e-2
adam_epsilon: 1e-8
max_grad_norm: 1.0

# Logging and checkpointing
logging_dir: "logs"
report_to: "tensorboard"
checkpointing_steps: 4000
checkpoints_total_limit: null
mixed_precision: "fp16"
enable_xformers_memory_efficient_attention: false
set_grads_to_none: false

# Validation
validation_steps: 1000
validation_sanity_check: true
tracker_project_name: "train_controlnet"
num_validation_images: 4
vis_dir: vis